In [1]:
'''
metadata info: column names in the three data files
usr_csv_columns = ['user_id','friends', 'name','review_count','compliment_cute', 'compliment_funny', 'funny', 'compliment_photos', 'compliment_hot', 'compliment_more', 'compliment_plain', 'average_stars', 'review_count', 'compliment_list', 'fans', 'useful', 'cool', 'yelping_since', 'compliment_note', 'elite', 'compliment_profile', 'compliment_cool', 'compliment_writer']
review_csv_columns = ['funny', 'review_id', 'date', 'useful', 'cool', 'user_id', 'business_id', 'text', 'stars']
business_csv_columns = ['city', 'business_id', 'address', 'state', 'categories', 'review_count', 'is_open', 'attributes', 'postal_code', 'name', 'latitude', 'stars', 'hours', 'longitude']

'''
import pandas as pd

In [4]:
path= "C:/Users/amogh/Appledore/projects/Graph-Embedding-based-Recommendation/data/review.csv"
review_df = pd.read_csv(path)

In [108]:
'''
Filter reviews for 2018
'''
start_date = '2018-01-01 00:00:00'
end_date = '2018-12-31 00:00:00'
mask = (review_df['date'] > start_date) & (review_df['date'] <= end_date)
review_df = review_df.loc[mask]
review_df.head()

,funny,review_id,date,useful,cool,user_id,business_id,text,stars
3,0,yi0R0Ugj_xUx_Nek0-_Qig,2018-01-09 20:56:38,0,0,dacAIZ6fTM6mqwW5uxkskg,ikCg8xy5JIg_NGPx-MSIDA,Went in for a lunch. Steak sandwich was delici...,5.0
4,0,11a8sVPMUFtaC7_ABRkmtw,2018-01-30 23:07:38,7,0,ssoyf2_x0EQMed6fgHeMyQ,b1b1eb3uo-w561D0ZfCEiQ,Today was my second out of three sessions I ha...,1.0
13,0,qlXw1JQ0UodW7qrmVgwCXw,2018-04-27 20:25:26,0,0,bAhqAPoWaZYcyYi7bs024Q,LUN6swQYa4xJKaM_UEUOEw,Michael from Red Carpet VIP is amazing ! I rea...,4.0
38,0,vBRxlgkpDTXjWiYBp1V6GA,2018-02-01 19:01:16,0,0,wNyiw6GfVfn5Kphqmux1gw,5OZlLXjU0FXUbrw8Scja6g,They keep there appointments on time and are p...,1.0
42,0,NqYSX93Amv4sd5pPPr3Gag,2018-10-04 11:20:42,0,0,zFYFuufYWQSPj0r5lrKQKg,wJj1EwYcXHdvA9zKqmb5hQ,I called the number provided and same day they...,5.0

In [109]:
len(review_df) #Total reviews for 2018

1177662

In [110]:
review_df.to_csv('../data/2018-review.csv', encoding='utf-8') #Writing 2018 reviews to a file

In [111]:
path= "C:/Users/amogh/Appledore/projects/Graph-Embedding-based-Recommendation/data/business.csv"
b_df = pd.read_csv(path)

In [118]:
mask = b_df['city']=='Las Vegas'
business_df = b_df.loc[mask] #Filter business of Las Vegas
business_df['categories'].replace('', np.nan, inplace=True) #replaces '' with NaN
business_df.dropna(subset=['categories'], inplace=True) #removes NaN value
business_df = business_df[business_df['categories'].str.match('Restaurants')] #Select only places with are Restaurants

C:\Users\amogh\Anaconda3\envs\conda-yelp\lib\site-packages\pandas\core\generic.py:5886: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
C:\Users\amogh\Anaconda3\envs\conda-yelp\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [119]:
business_df.head()

,city,business_id,address,state,categories,review_count,is_open,attributes,postal_code,name,latitude,stars,hours,longitude
17,Las Vegas,PZ-LZzSlhSe9utkQYU8pFg,"1775 E Tropicana Ave, Ste 29",NV,"Restaurants, Italian",40,0,"{'RestaurantsAttire': ""'casual'"", 'WiFi': ""u'n...",89119,Carluccio's Tivoli Gardens,36.100016,4.0,NaN,-115.128528
111,Las Vegas,X8mtoSxY8whtmbDlj0D3Aw,4343 N Rancho Dr,NV,"Restaurants, Chinese",4,1,NaN,89030,Imperial Asian Buffet,36.238596,2.0,NaN,-115.233331
135,Las Vegas,bJP4l_BGq2CudEu0m-wNjg,"Artisan Hotel, 1501 W Sahara Ave",NV,"Restaurants, Pizza, Italian, American (New)",3,0,"{'RestaurantsAttire': ""'dressy'"", 'WiFi': ""u'n...",89102,Artisan Fine Dining Room,36.143672,2.0,"{'Saturday': '16:0-0:0', 'Tuesday': '16:0-0:0'...",-115.169792
240,Las Vegas,0G83H_zoum-Q4bWU2olTqQ,"4012 S Rainbow Blvd, Ste J",NV,"Restaurants, Food, Delis, Desserts, Bakeries, ...",39,1,"{'RestaurantsAttire': ""u'casual'"", 'WiFi': ""u'...",89103,Bonjour Bakery & Deli,36.116169,4.5,"{'Saturday': '8:0-15:0', 'Tuesday': '8:0-15:0'...",-115.241852
494,Las Vegas,k2b3niokS_tosjah_rzCPw,6720 Sky Pointe Dr,NV,"Restaurants, Pizza",303,1,"{'RestaurantsAttire': ""u'casual'"", 'WiFi': ""u'...",89131,Metro Pizza,36.283669,3.5,"{'Saturday': '11:0-22:0', 'Tuesday': '11:0-22:...",-115.270284

In [120]:
len(business_df) #Total number of business ids after removing restuarent with NaN values

1840

In [137]:
business_df.to_csv('../data/2018-Business-LasVegas-Restaurants.csv', encoding='utf-8')

In [127]:
review_Vegas_df = review_df[review_df['business_id'].isin(business_df['business_id'])]
len(review_Vegas_df) #Reviews now only for 2018 Las Vegas restuarant

46424

In [126]:
review_Vegas_df.head()

,funny,review_id,date,useful,cool,user_id,business_id,text,stars
178,0,w1I8U4cJ4QGaXA98ImNrbA,2018-08-04 20:22:15,0,0,rJNdeta-dYO2YcJ3u5JxnA,faPVqws-x-5k2CQKDNtHxw,"Service was amazing, Christina was extremely t...",5.0
222,0,2ofBIfK5Bx6SPo3K5_ITCw,2018-04-27 18:31:23,2,1,IZPYIYdr05FvjKva2986aw,a0v7Si0DK4cIko7AQY4YXg,Go. Seriously. You will not be disappointed on...,5.0
609,0,0ZHXbGl9o3fuynuTDV1BJA,2018-08-14 04:23:18,0,0,kdDTqKBbfNZeKEbWAcqZWQ,_j2EtQtgLuXGRBfbM5YwZA,Located at the Venetian Hotel in Las Vegas. Gr...,4.0
942,0,Gu4tg0JA1Y1vV1Bi9p6HHg,2018-08-04 20:39:11,0,0,1kbHR5IroDiZD0npir8OLw,meMEbONCUMmY6MiamrcufA,Great Columbian street food place. A lot of o...,5.0
1018,0,fmlSIaSAhMBTMWIKyDbHpg,2018-09-25 03:17:10,0,0,yKi6CFQxwGeXXPDqnSWZrA,2vr2yGIzSehe_ITFamNpyw,Fu ck everything in the past...this place is b...,5.0

In [138]:
review_Vegas_df.to_csv('../data/2018-review-LasVegas-Restaurants.csv', encoding='utf-8')

In [139]:
#'gbQN7vr_caG_A1ugSmGhWg' in business_df['business_id'].unique()

In [140]:
review_business_df=business_df.merge(review_df,how='left',on='business_id')

In [141]:
review_business_df.head()

,city,business_id,address,state,categories,review_count,is_open,attributes,postal_code,name,...,hours,longitude,funny,review_id,date,useful,cool,user_id,text,stars_y
0,Las Vegas,PZ-LZzSlhSe9utkQYU8pFg,"1775 E Tropicana Ave, Ste 29",NV,"Restaurants, Italian",40,0,"{'RestaurantsAttire': ""'casual'"", 'WiFi': ""u'n...",89119,Carluccio's Tivoli Gardens,...,NaN,-115.128528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Las Vegas,X8mtoSxY8whtmbDlj0D3Aw,4343 N Rancho Dr,NV,"Restaurants, Chinese",4,1,NaN,89030,Imperial Asian Buffet,...,NaN,-115.233331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Las Vegas,bJP4l_BGq2CudEu0m-wNjg,"Artisan Hotel, 1501 W Sahara Ave",NV,"Restaurants, Pizza, Italian, American (New)",3,0,"{'RestaurantsAttire': ""'dressy'"", 'WiFi': ""u'n...",89102,Artisan Fine Dining Room,...,"{'Saturday': '16:0-0:0', 'Tuesday': '16:0-0:0'...",-115.169792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Las Vegas,0G83H_zoum-Q4bWU2olTqQ,"4012 S Rainbow Blvd, Ste J",NV,"Restaurants, Food, Delis, Desserts, Bakeries, ...",39,1,"{'RestaurantsAttire': ""u'casual'"", 'WiFi': ""u'...",89103,Bonjour Bakery & Deli,...,"{'Saturday': '8:0-15:0', 'Tuesday': '8:0-15:0'...",-115.241852,0.0,Xx5yG7R0NkuqgKbnjnljHQ,2018-04-15 23:31:43,0.0,0.0,MBA2Fl9fcbqMyQ8WTG_X8Q,Our airbnb host suggested this charming bistro...,5.0
4,Las Vegas,0G83H_zoum-Q4bWU2olTqQ,"4012 S Rainbow Blvd, Ste J",NV,"Restaurants, Food, Delis, Desserts, Bakeries, ...",39,1,"{'RestaurantsAttire': ""u'casual'"", 'WiFi': ""u'...",89103,Bonjour Bakery & Deli,...,"{'Saturday': '8:0-15:0', 'Tuesday': '8:0-15:0'...",-115.241852,0.0,CRt1FyzblRdCNR9Vti1A3g,2018-01-10 23:32:59,0.0,0.0,7_b1jlVB8dg0ufRs07mzeA,I love this spot! The food is delicious and th...,5.0

In [142]:
len(review_business_df)

47115

In [143]:
review_business_df.to_csv('../data/2018-review-business-merged.csv', encoding='utf-8')